// Contexto para obtener todas las peliculas del cine
import { createContext, useContext, useState } from "react";

const MoviesContext = createContext()

export default function MoviesProvider(props){
    const [movies, setMovies] = useState([
        {
            id: 1,
            title: "Zootopia 2",
            poster: "movies/zootopia.jpg",
            genre: "Family",
            description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
            duration: "2 hr 45 min",
            releaseDate: "2026-08-25",
            status: 1,
            director: "James Cameron",
            producer: "James Cameron, Jon Landau",
            casting: "Sam Worthington, Zoe Saldana, Sigourney Weaver",
            showtimes: [
                {
                    id: 1,
                    date: "2026-07-13",
                    room: "1",
                    hour: "13:00",
                    language: "Spanish",
                    roomType: "regular",
                },
                {
                    id: 2,
                    date: "2026-07-13",
                    room: "1",
                    hour: "13:30",
                    language: "English",
                    roomType: "regular",
                },
                {
                    id: 3,
                    date: "2026-07-13",
                    room: "1",
                    hour: "14:20",
                    language: "English",
                    roomType: "cxc",
                },
                {
                    id: 4,
                    date: "2026-07-13",
                    room: "1",
                    hour: "15:00",
                    language: "English",
                    roomType: "vip",
                },
                {
                    id: 5,
                    date: "2026-07-13",
                    room: "1",
                    hour: "16:10",
                    language: "English",
                    roomType: "imax",
                },
                {
                    id: 6,
                    date: "2026-07-13",
                    room: "1",
                    hour: "18:00",
                    language: "Spanish",
                    roomType: "regular",
                },
                {
                    id: 7,
                    date: "2026-07-13",
                    room: "1",
                    hour: "20:00",
                    language: "Spanish",
                    roomType: "fourd",
                },
            ],
        },
        {
            id: 2,
            title: "Now You See Me 3",
            poster: "movies/now_you_see_me.jpg",
            genre: "Action",
            description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
            duration: "2 hr 45 min",
            releaseDate: "2026-08-25",
            status: 2,
            director: "James Cameron",
            producer: "James Cameron, Jon Landau",
            casting: "Sam Worthington, Zoe Saldana, Sigourney Weaver",
            showtimes: [
                {
                    id: 1,
                    date: "2026-07-13",
                    room: "1",
                    hour: "13:00",
                    language: "Spanish",
                    roomType: "regular",
                },
                {
                    id: 2,
                    date: "2026-07-13",
                    room: "1",
                    hour: "13:30",
                    language: "English",
                    roomType: "regular",
                },
                {
                    id: 3,
                    date: "2026-07-13",
                    room: "1",
                    hour: "14:20",
                    language: "English",
                    roomType: "cxc",
                },
                {
                    id: 4,
                    date: "2026-07-13",
                    room: "1",
                    hour: "15:00",
                    language: "English",
                    roomType: "vip",
                },
                {
                    id: 5,
                    date: "2026-07-13",
                    room: "1",
                    hour: "16:10",
                    language: "English",
                    roomType: "imax",
                },
                {
                    id: 6,
                    date: "2026-07-13",
                    room: "1",
                    hour: "18:00",
                    language: "Spanish",
                    roomType: "regular",
                },
                {
                    id: 7,
                    date: "2026-07-13",
                    room: "1",
                    hour: "20:00",
                    language: "Spanish",
                    roomType: "fourd",
                },
            ],
        },
        {
            id: 3,
            title: "Avatar: Ash and Fire",
            poster: "movies/avatar.jpg",
            genre: "Science Fiction",
            description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
            duration: "2 hr 45 min",
            releaseDate: "2026-08-25",
            status: 1,
            director: "James Cameron",
            producer: "James Cameron, Jon Landau",
            casting: "Sam Worthington, Zoe Saldana, Sigourney Weaver",
            showtimes: [
                {
                    id: 1,
                    date: "2026-07-13",
                    room: "1",
                    hour: "13:00",
                    language: "Spanish",
                    roomType: "regular",
                },
                {
                    id: 2,
                    date: "2026-07-13",
                    room: "1",
                    hour: "13:30",
                    language: "English",
                    roomType: "regular",
                },
                {
                    id: 3,
                    date: "2026-07-13",
                    room: "1",
                    hour: "14:20",
                    language: "English",
                    roomType: "cxc",
                },
                {
                    id: 4,
                    date: "2026-07-13",
                    room: "1",
                    hour: "15:00",
                    language: "English",
                    roomType: "vip",
                },
                {
                    id: 5,
                    date: "2026-07-13",
                    room: "1",
                    hour: "16:10",
                    language: "English",
                    roomType: "imax",
                },
                {
                    id: 6,
                    date: "2026-07-13",
                    room: "1",
                    hour: "18:00",
                    language: "Spanish",
                    roomType: "regular",
                },
                {
                    id: 7,
                    date: "2026-07-13",
                    room: "1",
                    hour: "20:00",
                    language: "Spanish",
                    roomType: "fourd",
                },
            ],
        },
        {
            id: 4,
            title: "Tron: Ares",
            poster: "movies/tron.jpg",
            genre: "Science Fiction",
            description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
            duration: "2 hr 45 min",
            releaseDate: "2026-08-25",
            status: 1,
            director: "James Cameron",
            producer: "James Cameron, Jon Landau",
            casting: "Sam Worthington, Zoe Saldana, Sigourney Weaver",
            showtimes: [
                {
                    id: 1,
                    date: "2026-07-13",
                    room: "1",
                    hour: "13:00",
                    language: "Spanish",
                    roomType: "regular",
                },
                {
                    id: 2,
                    date: "2026-07-13",
                    room: "1",
                    hour: "13:30",
                    language: "English",
                    roomType: "regular",
                },
                {
                    id: 3,
                    date: "2026-07-13",
                    room: "1",
                    hour: "14:20",
                    language: "English",
                    roomType: "cxc",
                },
                {
                    id: 4,
                    date: "2026-07-13",
                    room: "1",
                    hour: "15:00",
                    language: "English",
                    roomType: "vip",
                },
                {
                    id: 5,
                    date: "2026-07-13",
                    room: "1",
                    hour: "16:10",
                    language: "English",
                    roomType: "imax",
                },
                {
                    id: 6,
                    date: "2026-07-13",
                    room: "1",
                    hour: "18:00",
                    language: "Spanish",
                    roomType: "regular",
                },
                {
                    id: 7,
                    date: "2026-07-13",
                    room: "1",
                    hour: "20:00",
                    language: "Spanish",
                    roomType: "fourd",
                },
            ],
        },
        {
            id: 5,
            title: "Star Wars: Revenge of the Sith",
            poster: "movies/star_wars_rots.jpg",
            genre: "Science Fiction",
            description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
            duration: "2 hr 45 min",
            releaseDate: "2026-08-25",
            status: 1,
            director: "James Cameron",
            producer: "James Cameron, Jon Landau",
            casting: "Sam Worthington, Zoe Saldana, Sigourney Weaver",
            showtimes: [
                {
                    id: 1,
                    date: "2026-07-13",
                    room: "1",
                    hour: "13:00",
                    language: "Spanish",
                    roomType: "regular",
                },
                {
                    id: 2,
                    date: "2026-07-13",
                    room: "1",
                    hour: "13:30",
                    language: "English",
                    roomType: "regular",
                },
                {
                    id: 3,
                    date: "2026-07-13",
                    room: "1",
                    hour: "14:20",
                    language: "English",
                    roomType: "cxc",
                },
                {
                    id: 4,
                    date: "2026-07-13",
                    room: "1",
                    hour: "15:00",
                    language: "English",
                    roomType: "vip",
                },
                {
                    id: 5,
                    date: "2026-07-13",
                    room: "1",
                    hour: "16:10",
                    language: "English",
                    roomType: "imax",
                },
                {
                    id: 6,
                    date: "2026-07-13",
                    room: "1",
                    hour: "18:00",
                    language: "Spanish",
                    roomType: "regular",
                },
                {
                    id: 7,
                    date: "2026-07-13",
                    room: "1",
                    hour: "20:00",
                    language: "Spanish",
                    roomType: "fourd",
                },
            ],
        },
        {
            id: 6,
            title: "Five Nights at Freddy's 2",
            poster: "movies/fnaf_2.jpg",
            genre: "Terror",
            description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
            duration: "2 hr 45 min",
            releaseDate: "2026-08-25",
            status: 3,
            director: "James Cameron",
            producer: "James Cameron, Jon Landau",
            casting: "Sam Worthington, Zoe Saldana, Sigourney Weaver",
            showtimes: [
                {
                    id: 1,
                    date: "2026-07-13",
                    room: "1",
                    hour: "13:00",
                    language: "Spanish",
                    roomType: "regular",
                },
                {
                    id: 2,
                    date: "2026-07-13",
                    room: "1",
                    hour: "13:30",
                    language: "English",
                    roomType: "regular",
                },
                {
                    id: 3,
                    date: "2026-07-13",
                    room: "1",
                    hour: "14:20",
                    language: "English",
                    roomType: "cxc",
                },
                {
                    id: 4,
                    date: "2026-07-13",
                    room: "1",
                    hour: "15:00",
                    language: "English",
                    roomType: "vip",
                },
                {
                    id: 5,
                    date: "2026-07-13",
                    room: "1",
                    hour: "16:10",
                    language: "English",
                    roomType: "imax",
                },
                {
                    id: 6,
                    date: "2026-07-13",
                    room: "1",
                    hour: "18:00",
                    language: "Spanish",
                    roomType: "regular",
                },
                {
                    id: 7,
                    date: "2026-07-13",
                    room: "1",
                    hour: "20:00",
                    language: "Spanish",
                    roomType: "fourd",
                },
            ],
        },
    ]);

    return (
        <MoviesContext.Provider
            value={{movies, setMovies}}>
            {props.children}
        </MoviesContext.Provider>
    )
}

export const useMovies = () => useContext(MoviesContext);